version: "3.3"

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - opentelemetry_network

  postgres:
    container_name: opentelemetry_postgres
    build:
      context: database
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - data_network

  app1:
    container_name: app1
    build:
      context: app1
      dockerfile: app1.Dockerfile
    depends_on:
      - app2
    ports:
      - "8000:8000"
    networks:
      - opentelemetry_network

  app2:
    container_name: app2
    build:
      context: app2
      dockerfile: app2.Dockerfile
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    networks:
      - data_network
      - opentelemetry_network

  app3:
    container_name: app3
    build:
      context: app3
      dockerfile: app3.Dockerfile
    environment:
#      not safe
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-""}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-""}
    ports:
      - "8002:8002"
    networks:
      - opentelemetry_network


networks:
  opentelemetry_network:
  data_network: