version: "3.3"

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - opentelemetry_network

  postgres:
    container_name: opentelemetry_postgres
    build:
      context: database
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - data_network

  app1:
    container_name: app1
    build:
      context: app1
      dockerfile: app1.Dockerfile
    depends_on:
      - app2
      - app3
      - otel-collector
    ports:
      - "8000:8000"
    networks:
      - opentelemetry_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app

  app2:
    container_name: app2
    build:
      context: app2
      dockerfile: app2.Dockerfile
    depends_on:
      - postgres
      - otel-collector
    ports:
      - "8001:8001"
    networks:
      - data_network
      - opentelemetry_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app

  app3:
    container_name: app3
    build:
      context: app3
      dockerfile: app3.Dockerfile
    environment:
#      not safe
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-""}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY:-""}
    ports:
      - "8002:8002"
    depends_on:
      - otel-collector
    networks:
      - opentelemetry_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: app

  fluentd:
    image: fluent/fluentd
    container_name: fluentd
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
    environment:
      FLUENTD_CONF: fluentd.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - opentelemetry_network

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "8006" # fluentd receiver
      - "9411"   # Zipkin receiver
      - "4317:4317"        # OTLP gRPC receiver
    depends_on:
      - zipkin
#      - fluentd
    networks:
      - opentelemetry_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yaml/:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - opentelemetry_network

networks:
  opentelemetry_network:
  data_network: