#https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
#  not working yet
#  fluentforward:
#    endpoint: 0.0.0.0:8006
  zipkin:
  otlp:
    protocols:
      grpc:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'flaskapp1'
          metrics_path: '/metrics'
          scrape_interval: 10s
          static_configs:
            - targets: [ 'app1:8000' ]

#https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
  logging:

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

#https://opentelemetry.io/docs/collector/configuration/#processors
processors:
  batch:
#    send_batch_max_size: 0 #default
#    send_batch_size: 8192 #default
#    timeout: 200ms #default

#https://opentelemetry.io/docs/collector/configuration/#extensions
extensions:
  health_check:

#https://opentelemetry.io/docs/collector/configuration/#service
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [batch]
      exporters: [logging, zipkin]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [logging, prometheus]
#    logs:
#      receivers: [ fluentforward ]
#      processors: [ batch ]
#      exporters: [ logging ]
